# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnwzIOhxSFImS89z1jccEfediPJZn8po
"""

# Oddiy kalkulyator
def calculator():
    print("Oddiy kalkulyator")
    a = float(input("Birinchi raqamni kiriting: "))
    b = float(input("Ikkinchi raqamni kiriting: "))
    amal = input("Amalni kiriting (+, -, *, /): ")

    if amal == '+':
        print(f"Natija: {a + b}")
    elif amal == '-':
        print(f"Natija: {a - b}")
    elif amal == '*':
        print(f"Natija: {a * b}")
    elif amal == '/':
        if b != 0:
            print(f"Natija: {a / b}")
        else:
            print("Nolga bo'lish mumkin emas!")

if __name__ == "__main__":
    calculator()